export const FETCH_USER = 'FETCH_USER';
export const FETCH_CART_PRODUCT = 'FETCH_CART_PRODUCT';
export const PRODUCT_FETCH = 'PRODUCT_FETCH';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const BUY_PRODUCT = 'BUY_PRODUCT';